import { EditorView } from "@codemirror/view"

// Markdown 编辑器主题与语法标记样式定义。
export const editorTheme = EditorView.theme(
  {
    "&": {
      height: "100%",
      backgroundColor: "#212121",
      color: "#e5e5e5",
      fontSize: "14px",
    },
    ".cm-content": {
      minHeight: "100%",
      padding: "12px 16px calc(50cqh - 0.925em - 12px)",
      caretColor: "#ffffff",
      fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
      lineHeight: "1.65",
    },
    ".cm-line": {
      // 内容行高
      lineHeight: "1.85",
      // 作为行内操作按钮（代码块/模板块右上角）的定位参照，实现垂直居中。
      position: "relative",
    },
    ".cm-scroller": {
      containerType: "size",
      overflow: "auto",
      scrollbarGutter: "stable",
    },
    ".cm-gutters": {
      minHeight: "100%",
      borderRight: "1px solid rgba(255, 255, 255, 0.05)",
      backgroundColor: "#212121",
      color: "rgba(255, 255, 255, 0.3)",
    },
    ".cm-lineNumbers .cm-gutterElement": {
      paddingLeft: "10px",
      paddingRight: "6px",
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "flex-end",
      boxSizing: "border-box",
      height: "1.65em",
      lineHeight: "1.65em",
    },
    ".cm-foldGutter .cm-gutterElement": {
      cursor: "pointer",
      color: "rgba(255, 255, 255, 0.35)",
      transition: "color 0.15s ease",
      display: "flex",
      alignItems: "flex-start",
      justifyContent: "center",
      paddingLeft: "4px",
      paddingRight: "8px",
      boxSizing: "border-box",
    },
    ".cm-gutters > .cm-foldGutter:first-child .cm-gutterElement": {
      paddingLeft: "8px",
      paddingRight: "8px",
    },
    ".cm-foldGutter .cm-gutterElement:hover": {
      color: "#ffffff",
    },
    ".cm-fold-marker": {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      width: "12px",
      height: "1.65em",
      color: "currentColor",
    },
    ".cm-foldPlaceholder": {
      backgroundColor: "rgba(255, 255, 255, 0.08)",
      border: "none",
      color: "rgba(255, 255, 255, 0.5)",
      borderRadius: "3px",
      padding: "2px 4px",
      margin: "0 4px",
      cursor: "pointer",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      verticalAlign: "middle",
      userSelect: "none",
      transition: "all 0.15s cubic-bezier(0.4, 0, 0.2, 1)",
    },
    ".cm-foldPlaceholder:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.18)",
      color: "#ffffff",
    },
    ".cm-activeLine": {
      backgroundColor: "rgba(255, 255, 255, 0.035)",
    },
    ".cm-activeLineGutter": {
      backgroundColor: "rgba(255, 255, 255, 0.035)",
    },
    ".cm-selectionBackground, &.cm-focused .cm-selectionBackground": {
      backgroundColor: "rgba(255, 255, 255, 0.18)",
    },
    ".cm-cursor, .cm-dropCursor": {
      borderLeftColor: "#ffffff",
    },
    ".cm-tooltip": {
      backgroundColor: "#2b2b2b",
      border: "1px solid rgba(255, 255, 255, 0.12)",
      borderRadius: "6px",
      boxShadow: "0 8px 24px rgba(0, 0, 0, 0.5)",
      padding: "6px",
      zIndex: 100,
    },
    ".cm-md-heading-marker, .cm-md-heading-marker *": {
      color: "#e9a339 !important",
      fontWeight: "700",
    },
    ".cm-md-strong-marker, .cm-md-strong-marker *": {
      color: "#fb923c !important",
      fontWeight: "700",
    },
    ".cm-md-emphasis-marker, .cm-md-emphasis-marker *": {
      color: "#f472b6 !important",
      fontWeight: "700",
    },
    ".cm-md-table-marker, .cm-md-table-marker *": {
      color: "#38bdf8 !important",
      fontWeight: "700",
    },
    ".cm-md-task-marker, .cm-md-task-marker *": {
      color: "#a3e635 !important",
      fontWeight: "700",
    },
    ".cm-md-unordered-list-marker, .cm-md-unordered-list-marker *": {
      color: "#2dd4bf !important",
      fontWeight: "700",
    },
    ".cm-md-ordered-list-marker, .cm-md-ordered-list-marker *": {
      color: "#c084fc !important",
      fontWeight: "700",
    },
    ".cm-md-code-fence-marker, .cm-md-code-fence-marker *": {
      color: "#e879f9 !important",
      fontWeight: "700",
    },
    ".cm-md-template-marker, .cm-md-template-marker *": {
      color: "#818cf8 !important",
      fontWeight: "700",
    },
    ".cm-md-template-command, .cm-md-template-command *": {
      color: "#c4b5fd !important",
      fontWeight: "700",
      backgroundColor: "rgba(196, 181, 253, 0.12) !important",
      padding: "1px 6px !important",
      borderRadius: "3px !important",
    },
    ".cm-md-template-command-addTemplate, .cm-md-template-command-addTemplate *": {
      color: "#34d399 !important",
      backgroundColor: "rgba(52, 211, 153, 0.15) !important",
    },
    ".cm-md-template-command-bugTemplate, .cm-md-template-command-bugTemplate *": {
      color: "#fb7185 !important",
      backgroundColor: "rgba(251, 113, 133, 0.15) !important",
    },
    ".cm-md-template-command-refactorTemplate, .cm-md-template-command-refactorTemplate *": {
      color: "#c084fc !important",
      backgroundColor: "rgba(192, 132, 252, 0.15) !important",
    },
    ".cm-md-template-command-commonTemplate, .cm-md-template-command-commonTemplate *": {
      color: "#38bdf8 !important",
      backgroundColor: "rgba(56, 189, 248, 0.15) !important",
    },
    ".cm-md-template-command-styleTemplate, .cm-md-template-command-styleTemplate *": {
      color: "#f472b6 !important",
      backgroundColor: "rgba(244, 114, 182, 0.15) !important",
    },
    ".cm-md-template-flag, .cm-md-template-flag *": {
      color: "#a5b4fc !important",
      backgroundColor: "rgba(165, 180, 252, 0.14) !important",
      padding: "1px 5px !important",
      borderRadius: "3px !important",
      fontWeight: "700 !important",
    },
    ".cm-md-template-title, .cm-md-template-title *": {
      color: "#fde68a !important",
      backgroundColor: "rgba(253, 230, 138, 0.18) !important",
      textDecoration: "underline",
      textDecorationColor: "rgba(253, 230, 138, 0.6)",
      padding: "1px 6px !important",
      borderRadius: "3px !important",
    },
    ".cm-md-bracket-content-marker, .cm-md-bracket-content-marker *": {
      textDecoration: "underline",
      textDecorationColor: "rgba(255, 255, 255, 0.4)",
    },
    ".cm-md-template-done, .cm-md-template-done *": {
      color: "#34d399 !important",
      backgroundColor: "rgba(52, 211, 153, 0.15) !important",
      padding: "1px 6px !important",
      borderRadius: "3px !important",
    },
    ".cm-md-template-in-progress, .cm-md-template-in-progress *": {
      color: "#fbbf24 !important",
      backgroundColor: "rgba(251, 191, 36, 0.15) !important",
      padding: "1px 6px !important",
      borderRadius: "3px !important",
    },
    ".cm-md-template-id, .cm-md-template-id *": {
      color: "#f0abfc !important",
      backgroundColor: "rgba(240, 171, 252, 0.14) !important",
      padding: "1px 6px !important",
      borderRadius: "3px !important",
      fontWeight: "600 !important",
    },
    ".cm-md-template-wt, .cm-md-template-wt *": {
      color: "#22d3ee !important",
      backgroundColor: "rgba(34, 211, 238, 0.14) !important",
      padding: "1px 6px !important",
      borderRadius: "3px !important",
      fontWeight: "600 !important",
    },
    ".cm-md-code-fence-language, .cm-md-code-fence-language *": {
      color: "#38bdf8 !important",
      fontWeight: "700",
      backgroundColor: "rgba(56, 189, 248, 0.12) !important",
      padding: "1px 6px !important",
      borderRadius: "3px !important",
    },
    ".cm-md-code-fence-start-line": {
      borderTop: "1.5px solid rgba(255, 255, 255, 0.15)",
      borderLeft: "1.5px solid rgba(255, 255, 255, 0.15)",
      borderRight: "1.5px solid rgba(255, 255, 255, 0.15)",
      borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
      borderTopLeftRadius: "6px",
      borderTopRightRadius: "6px",
      backgroundColor: "rgba(255, 255, 255, 0.035)",
      boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.15), 0 3px 6px rgba(0, 0, 0, 0.3)",
      paddingLeft: "8px",
      paddingTop: "4px",
      paddingBottom: "4px",
    },
    ".cm-md-code-fence-middle-line": {
      borderLeft: "1.5px solid rgba(255, 255, 255, 0.15)",
      borderRight: "1.5px solid rgba(255, 255, 255, 0.15)",
      backgroundColor: "rgba(255, 255, 255, 0.035)",
      boxShadow: "inset 1px 0 0 rgba(255, 255, 255, 0.08), inset -1px 0 0 rgba(0, 0, 0, 0.4)",
      paddingLeft: "8px",
    },
    ".cm-md-code-fence-end-line": {
      borderBottom: "1.5px solid rgba(255, 255, 255, 0.15)",
      borderLeft: "1.5px solid rgba(255, 255, 255, 0.15)",
      borderRight: "1.5px solid rgba(255, 255, 255, 0.15)",
      borderBottomLeftRadius: "6px",
      borderBottomRightRadius: "6px",
      backgroundColor: "rgba(255, 255, 255, 0.035)",
      boxShadow: "inset 0 -1px 0 rgba(0, 0, 0, 0.5), 0 3px 6px rgba(0, 0, 0, 0.3)",
      paddingLeft: "8px",
      paddingBottom: "4px",
    },
    ".cm-md-template-start-line": {
      borderTop: "1.5px solid rgba(129, 140, 248, 0.45)",
      borderLeft: "2px solid rgba(129, 140, 248, 0.45)",
      borderRight: "2px solid rgba(129, 140, 248, 0.45)",
      borderBottom: "1px solid rgba(129, 140, 248, 0.25)",
      borderTopLeftRadius: "6px",
      borderTopRightRadius: "6px",
      backgroundColor: "rgba(129, 140, 248, 0.06)",
      boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 4px 10px rgba(0, 0, 0, 0.35)",
      paddingLeft: "8px",
      // 模板块操作按钮绝对定位在行末，预留空间避免遮挡标题。
      paddingRight: "96px",
      boxSizing: "border-box",
      paddingTop: "4px",
      paddingBottom: "4px",
    },
    ".cm-md-template-middle-line": {
      borderLeft: "2px solid rgba(129, 140, 248, 0.45)",
      borderRight: "2px solid rgba(129, 140, 248, 0.45)",
      backgroundColor: "rgba(129, 140, 248, 0.06)",
      boxShadow: "inset 1px 0 0 rgba(255, 255, 255, 0.08), inset -1px 0 0 rgba(0, 0, 0, 0.4)",
      paddingLeft: "8px",
    },
    ".cm-md-template-end-line": {
      borderBottom: "2px solid rgba(129, 140, 248, 0.45)",
      borderLeft: "2px solid rgba(129, 140, 248, 0.45)",
      borderRight: "2px solid rgba(129, 140, 248, 0.45)",
      borderBottomLeftRadius: "6px",
      borderBottomRightRadius: "6px",
      backgroundColor: "rgba(129, 140, 248, 0.06)",
      boxShadow: "inset 0 -1px 0 rgba(0, 0, 0, 0.5), 0 4px 10px rgba(0, 0, 0, 0.35)",
      paddingLeft: "8px",
      paddingBottom: "4px",
    },
    ".cm-md-template-comment-line": {
      borderLeft: "2px solid rgba(129, 140, 248, 0.45)",
      borderRight: "2px solid rgba(129, 140, 248, 0.45)",
      backgroundColor: "rgba(129, 140, 248, 0.06)",
      boxShadow: "inset 1px 0 0 rgba(255, 255, 255, 0.08), inset -1px 0 0 rgba(0, 0, 0, 0.4)",
      paddingLeft: "8px",
    },
    ".cm-md-template-comment-line, .cm-md-template-comment-line *": {
      color: "#6b7280 !important",
      fontStyle: "italic !important",
    },
    ".cm-md-template-line-in-progress": {
      borderColor: "rgba(251, 191, 36, 0.35) !important",
    },
    ".cm-md-template-line-done": {
      borderColor: "rgba(52, 211, 153, 0.35) !important",
    },
    ".cm-md-template-hidden-line": {
      display: "none !important",
    },
    ".cm-md-supple-hidden-line": {
      display: "none !important",
    },
    ".cm-md-log-hidden-line": {
      display: "none !important",
    },
    ".cm-md-supple-command, .cm-md-supple-command *": {
      color: "#38bdf8 !important",
      backgroundColor: "rgba(56, 189, 248, 0.15) !important",
      padding: "1px 6px !important",
      borderRadius: "3px !important",
      fontWeight: "700 !important",
    },
    ".cm-md-supple-flag, .cm-md-supple-flag *": {
      color: "#38bdf8 !important",
      backgroundColor: "rgba(56, 189, 248, 0.1) !important",
      padding: "1px 5px !important",
      borderRadius: "3px !important",
      fontWeight: "700 !important",
    },
    ".cm-md-supple-marker, .cm-md-supple-marker *": {
      color: "#38bdf8 !important",
      fontWeight: "700",
    },
    ".cm-md-supple-start-line": {
      borderTop: "1.5px solid rgba(56, 189, 248, 0.45)",
      borderLeft: "2px solid rgba(56, 189, 248, 0.45)",
      borderRight: "2px solid rgba(56, 189, 248, 0.45)",
      borderBottom: "1px solid rgba(56, 189, 248, 0.25)",
      borderTopLeftRadius: "4px",
      borderTopRightRadius: "4px",
      backgroundColor: "rgba(56, 189, 248, 0.05)",
      paddingLeft: "8px",
      // 操作按钮绝对定位在行末，预留空间避免遮挡。
      paddingRight: "72px",
      boxSizing: "border-box",
      paddingTop: "4px",
      paddingBottom: "4px",
    },
    ".cm-md-supple-middle-line": {
      borderLeft: "2px solid rgba(56, 189, 248, 0.45)",
      borderRight: "2px solid rgba(56, 189, 248, 0.45)",
      backgroundColor: "rgba(56, 189, 248, 0.05)",
      paddingLeft: "8px",
    },
    ".cm-md-supple-end-line": {
      borderBottom: "1.5px solid rgba(56, 189, 248, 0.45)",
      borderLeft: "2px solid rgba(56, 189, 248, 0.45)",
      borderRight: "2px solid rgba(56, 189, 248, 0.45)",
      borderBottomLeftRadius: "4px",
      borderBottomRightRadius: "4px",
      backgroundColor: "rgba(56, 189, 248, 0.05)",
      paddingLeft: "8px",
      paddingBottom: "4px",
    },
    ".cm-md-log-command, .cm-md-log-command *": {
      color: "#2dd4bf !important",
      backgroundColor: "rgba(45, 212, 191, 0.15) !important",
      padding: "1px 6px !important",
      borderRadius: "3px !important",
      fontWeight: "700 !important",
    },
    ".cm-md-log-flag, .cm-md-log-flag *": {
      color: "#2dd4bf !important",
      backgroundColor: "rgba(45, 212, 191, 0.1) !important",
      padding: "1px 5px !important",
      borderRadius: "3px !important",
      fontWeight: "700 !important",
    },
    ".cm-md-log-marker, .cm-md-log-marker *": {
      color: "#2dd4bf !important",
      fontWeight: "700",
    },
    ".cm-md-log-start-line": {
      borderTop: "1.5px solid rgba(45, 212, 191, 0.45)",
      borderLeft: "2px solid rgba(45, 212, 191, 0.45)",
      borderRight: "2px solid rgba(45, 212, 191, 0.45)",
      borderBottom: "1px solid rgba(45, 212, 191, 0.25)",
      borderTopLeftRadius: "4px",
      borderTopRightRadius: "4px",
      backgroundColor: "rgba(45, 212, 191, 0.05)",
      paddingLeft: "8px",
      // 操作按钮绝对定位在行末，预留空间避免遮挡。
      paddingRight: "72px",
      boxSizing: "border-box",
      paddingTop: "4px",
      paddingBottom: "4px",
    },
    ".cm-md-log-middle-line": {
      borderLeft: "2px solid rgba(45, 212, 191, 0.45)",
      borderRight: "2px solid rgba(45, 212, 191, 0.45)",
      backgroundColor: "rgba(45, 212, 191, 0.05)",
      paddingLeft: "8px",
    },
    ".cm-md-log-end-line": {
      borderBottom: "1.5px solid rgba(45, 212, 191, 0.45)",
      borderLeft: "2px solid rgba(45, 212, 191, 0.45)",
      borderRight: "2px solid rgba(45, 212, 191, 0.45)",
      borderBottomLeftRadius: "4px",
      borderBottomRightRadius: "4px",
      backgroundColor: "rgba(45, 212, 191, 0.05)",
      paddingLeft: "8px",
      paddingBottom: "4px",
    },
    ".cm-md-inline-code-marker, .cm-md-inline-code-marker *": {
      color: "#fb7185 !important",
      fontWeight: "700",
    },
    ".cm-md-quote-marker, .cm-md-quote-marker *": {
      color: "#a5b4fc !important",
      fontWeight: "700",
    },
    ".cm-md-link-marker, .cm-md-link-marker *": {
      color: "#86efac !important",
      fontWeight: "700",
    },
    ".cm-md-strike-marker, .cm-md-strike-marker *": {
      color: "#fda4af !important",
      fontWeight: "700",
    },
    ".cm-md-separator-marker, .cm-md-separator-marker *": {
      color: "#fde047 !important",
      fontWeight: "700",
    },
    ".cm-md-file-mention, .cm-md-file-mention *": {
      color: "#eab308 !important",
      fontWeight: "500",
      textDecoration: "underline",
      textDecorationColor: "rgba(234, 179, 8, 0.4)",
    },
    ".cm-md-referenced-file-mention, .cm-md-referenced-file-mention *": {
      color: "#c4b5fd !important",
      fontWeight: "500",
      textDecoration: "underline",
      textDecorationColor: "rgba(196, 181, 253, 0.4)",
    },
    ".cm-md-reference-project, .cm-md-reference-project *": {
      color: "#c4b5fd !important",
      fontWeight: "500",
    },
    ".cm-md-reference-folder, .cm-md-reference-folder *": {
      color: "#d97706 !important",
      fontWeight: "500",
    },
    ".cm-md-reference-file, .cm-md-reference-file *": {
      color: "#7dd3fc !important",
      fontWeight: "500",
    },
    ".cm-md-reference-image, .cm-md-reference-image *": {
      color: "#f9a8d4 !important",
      fontWeight: "500",
    },
    ".cm-md-reference-common, .cm-md-reference-common *": {
      color: "#cbd5e1 !important",
      fontWeight: "500",
    },
    ".cm-md-code-fence-hidden-line": {
      display: "none !important",
    },
    ".cm-md-code-fence-start-line .cm-monospace, .cm-md-code-fence-middle-line .cm-monospace, .cm-md-code-fence-end-line .cm-monospace, .cm-md-template-start-line .cm-monospace, .cm-md-template-middle-line .cm-monospace, .cm-md-template-end-line .cm-monospace, .cm-md-template-comment-line .cm-monospace":
      {
        color: "inherit !important",
        backgroundColor: "transparent !important",
        padding: "0 !important",
        borderRadius: "0 !important",
      },
    ".cm-md-code-fence-start-line span:not(.cm-md-code-fence-language):not(.markdown-file-mention-node), .cm-md-code-fence-middle-line span:not(.markdown-file-mention-node), .cm-md-code-fence-end-line span:not(.markdown-file-mention-node), .cm-md-template-start-line span:not(.cm-md-template-command):not(.cm-md-template-flag):not(.cm-md-template-done):not(.cm-md-template-title):not(.markdown-file-mention-node), .cm-md-template-middle-line span:not(.markdown-file-mention-node), .cm-md-template-end-line span:not(.cm-md-template-command):not(.cm-md-template-flag):not(.cm-md-template-done):not(.cm-md-template-id):not(.cm-md-template-wt):not(.markdown-file-mention-node), .cm-md-template-comment-line span:not(.markdown-file-mention-node)":
      {
        backgroundColor: "transparent !important",
        padding: "0 !important",
        borderRadius: "0 !important",
      },
  },
  { dark: true },
)
