// 设置领域 IPC channel。
export const SETTINGS_CHANNELS = {
  getModelProviders: "settings:model-providers:get",
  saveModelProviders: "settings:model-providers:save",
  fetchModels: "settings:model-providers:fetch-models",
  getPermissionSettings: "settings:permissions:get",
  savePermissionSettings: "settings:permissions:save",
  getUiSettings: "settings:ui:get",
  saveUiSettings: "settings:ui:save",
  getCliSettings: "settings:cli:get",
  saveCliSettings: "settings:cli:save",
  getCliVersions: "settings:cli:get-versions",
  runCliLifecycleAction: "settings:cli:run-lifecycle-action",
  getLspSettings: "settings:lsp:get",
  saveLspSettings: "settings:lsp:save",
  getLspStatus: "settings:lsp:get-status",
  installLspServer: "settings:lsp:install-server",
  getMcpSettings: "settings:mcp:get",
  saveMcpSettings: "settings:mcp:save",
  reconnectMcp: "settings:mcp:reconnect",
} as const
