import { HighlightStyle } from "@codemirror/language"
import { EditorView } from "@codemirror/view"
import { tags } from "@lezer/highlight"

export const agentHighlightStyle = HighlightStyle.define([
  { tag: tags.heading, color: "#e9a339", fontWeight: "700" },
  { tag: tags.heading1, color: "#e9a339", fontWeight: "700" },
  { tag: tags.heading2, color: "#e9a339", fontWeight: "700" },
  { tag: tags.heading3, color: "#e9a339", fontWeight: "700" },
  { tag: tags.heading4, color: "#e9a339", fontWeight: "700" },
  { tag: tags.heading5, color: "#e9a339", fontWeight: "700" },
  { tag: tags.heading6, color: "#e9a339", fontWeight: "700" },
  { tag: tags.emphasis, color: "#fcd34d", fontStyle: "italic" },
  { tag: tags.strong, color: "#f59e0b", fontWeight: "700" },
  { tag: tags.strikethrough, color: "#fda4af", textDecoration: "line-through" },
  { tag: tags.link, color: "#93c5fd", textDecoration: "underline" },
  { tag: tags.url, color: "#67e8f9" },
  { tag: tags.quote, color: "#c4b5fd", fontStyle: "italic" },
  {
    tag: tags.monospace,
    color: "#fca5a5",
    backgroundColor: "rgba(252, 165, 165, 0.12)",
    borderRadius: "3px",
    padding: "1px 4px",
  },
  { tag: [tags.meta, tags.processingInstruction], color: "#7dd3fc" },
  { tag: tags.keyword, color: "#c4b5fd" },
  { tag: tags.string, color: "#86efac" },
  { tag: tags.number, color: "#fda4af" },
  { tag: tags.comment, color: "#94a3b8", fontStyle: "italic" },
  { tag: tags.variableName, color: "#e2e8f0" },
  { tag: tags.typeName, color: "#67e8f9" },
  { tag: tags.propertyName, color: "#93c5fd" },
  { tag: tags.operator, color: "#fcd34d" },
])

export const agentEditorTheme = EditorView.theme({
  "&": {
    height: "auto",
    minHeight: "44px",
    maxHeight: "244px",
    backgroundColor: "transparent",
    color: "rgba(255, 255, 255, 0.9)",
    fontSize: "12px",
    fontFamily: "inherit",
  },
  "&.cm-focused": {
    outline: "none",
  },
  ".cm-content": {
    minHeight: "44px",
    maxHeight: "244px",
    padding: "6px 4px 6px 4px",
    caretColor: "#ffffff",
    fontFamily: "inherit",
    fontSize: "12px",
    lineHeight: "20px",
  },
  ".cm-line": {
    lineHeight: "20px",
    padding: "0",
    position: "relative",
    fontSize: "12px",
  },
  ".cm-scroller": {
    overflow: "auto",
    fontFamily: "inherit",
    scrollPaddingTop: "4px",
    scrollPaddingBottom: "4px",
  },
  ".cm-placeholder": {
    color: "rgba(255, 255, 255, 0.35)",
    fontFamily: "inherit",
  },
  ".cm-cursor, .cm-dropCursor": {
    borderLeftColor: "#ffffff",
  },
  ".cm-selectionBackground, &.cm-focused .cm-selectionBackground": {
    backgroundColor: "rgba(255, 255, 255, 0.18)",
  },
  ".cm-activeLine": {
    backgroundColor: "transparent",
  },
  ".cm-md-heading-marker, .cm-md-heading-marker *": {
    color: "#e9a339 !important",
    fontWeight: "700",
    fontSize: "12px !important",
  },
  ".cm-md-strong-marker, .cm-md-strong-marker *": {
    color: "#fb923c !important",
    fontWeight: "700",
    fontSize: "12px !important",
  },
  ".cm-md-emphasis-marker, .cm-md-emphasis-marker *": {
    color: "#f472b6 !important",
    fontWeight: "700",
    fontSize: "12px !important",
  },
  ".cm-md-table-marker, .cm-md-table-marker *": {
    color: "#38bdf8 !important",
    fontWeight: "700",
    fontSize: "12px !important",
  },
  ".cm-md-task-marker, .cm-md-task-marker *": {
    color: "#a3e635 !important",
    fontWeight: "700",
    fontSize: "12px !important",
  },
  ".cm-md-unordered-list-marker, .cm-md-unordered-list-marker *": {
    color: "#2dd4bf !important",
    fontWeight: "700",
    fontSize: "12px !important",
  },
  ".cm-md-ordered-list-marker, .cm-md-ordered-list-marker *": {
    color: "#c084fc !important",
    fontWeight: "700",
    fontSize: "12px !important",
  },
  ".cm-md-code-fence-marker, .cm-md-code-fence-marker *": {
    color: "#e879f9 !important",
    fontWeight: "700",
    fontSize: "12px !important",
  },
  ".cm-md-code-fence-language, .cm-md-code-fence-language *": {
    color: "#38bdf8 !important",
    fontWeight: "700",
    fontSize: "12px !important",
    backgroundColor: "rgba(56, 189, 248, 0.12) !important",
    padding: "1px 6px !important",
    borderRadius: "3px !important",
  },
  ".cm-md-code-fence-start-line": {
    borderTop: "1px solid rgba(255, 255, 255, 0.08)",
    borderLeft: "1px solid rgba(255, 255, 255, 0.08)",
    borderRight: "1px solid rgba(255, 255, 255, 0.08)",
    borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
    borderTopLeftRadius: "6px",
    borderTopRightRadius: "6px",
    backgroundColor: "rgba(255, 255, 255, 0.015)",
    paddingLeft: "6px",
    paddingTop: "2px",
    paddingBottom: "2px",
  },
  ".cm-md-code-fence-middle-line": {
    borderLeft: "1px solid rgba(255, 255, 255, 0.08)",
    borderRight: "1px solid rgba(255, 255, 255, 0.08)",
    backgroundColor: "rgba(255, 255, 255, 0.015)",
    paddingLeft: "6px",
  },
  ".cm-md-code-fence-end-line": {
    borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
    borderLeft: "1px solid rgba(255, 255, 255, 0.08)",
    borderRight: "1px solid rgba(255, 255, 255, 0.08)",
    borderBottomLeftRadius: "6px",
    borderBottomRightRadius: "6px",
    backgroundColor: "rgba(255, 255, 255, 0.015)",
    paddingLeft: "6px",
    paddingBottom: "2px",
  },
  ".cm-md-code-fence-hidden-line": {
    display: "none !important",
  },
  ".cm-md-code-fence-start-line .cm-monospace, .cm-md-code-fence-middle-line .cm-monospace, .cm-md-code-fence-end-line .cm-monospace":
    {
      color: "inherit !important",
      backgroundColor: "transparent !important",
      padding: "0 !important",
      borderRadius: "0 !important",
    },
  ".cm-md-code-fence-start-line span:not(.cm-md-code-fence-language):not(.markdown-file-mention-node), .cm-md-code-fence-middle-line span:not(.markdown-file-mention-node), .cm-md-code-fence-end-line span:not(.markdown-file-mention-node)":
    {
      backgroundColor: "transparent !important",
      padding: "0 !important",
      borderRadius: "0 !important",
    },
  ".cm-md-inline-code-marker, .cm-md-inline-code-marker *": {
    color: "#fb7185 !important",
    fontWeight: "700",
  },
  ".cm-md-quote-marker, .cm-md-quote-marker *": {
    color: "#a5b4fc !important",
    fontWeight: "700",
  },
  ".cm-md-link-marker, .cm-md-link-marker *": {
    color: "#86efac !important",
    fontWeight: "700",
  },
  ".cm-md-strike-marker, .cm-md-strike-marker *": {
    color: "#fda4af !important",
    fontWeight: "700",
  },
  ".cm-md-separator-marker, .cm-md-separator-marker *": {
    color: "#fde047 !important",
    fontWeight: "700",
  },
  ".cm-md-bracket-content-marker, .cm-md-bracket-content-marker *": {
    fontSize: "12px !important",
    textDecoration: "underline",
    textDecorationColor: "rgba(255, 255, 255, 0.4)",
  },
  ".cm-md-template-marker, .cm-md-template-marker *": {
    color: "#818cf8 !important",
    fontWeight: "700",
    fontSize: "12px !important",
  },
  ".cm-md-template-command, .cm-md-template-command *": {
    color: "#c4b5fd !important",
    fontWeight: "700",
    fontSize: "12px !important",
    backgroundColor: "rgba(196, 181, 253, 0.12) !important",
    padding: "1px 6px !important",
    borderRadius: "3px !important",
  },
  ".cm-md-template-command-addTemplate, .cm-md-template-command-addTemplate *": {
    color: "#34d399 !important",
    backgroundColor: "rgba(52, 211, 153, 0.15) !important",
    fontSize: "12px !important",
  },
  ".cm-md-template-command-bugTemplate, .cm-md-template-command-bugTemplate *": {
    color: "#fb7185 !important",
    backgroundColor: "rgba(251, 113, 133, 0.15) !important",
    fontSize: "12px !important",
  },
  ".cm-md-template-command-refactorTemplate, .cm-md-template-command-refactorTemplate *": {
    color: "#c084fc !important",
    backgroundColor: "rgba(192, 132, 252, 0.15) !important",
    fontSize: "12px !important",
  },
  ".cm-md-template-command-commonTemplate, .cm-md-template-command-commonTemplate *": {
    color: "#38bdf8 !important",
    backgroundColor: "rgba(56, 189, 248, 0.15) !important",
    fontSize: "12px !important",
  },
  ".cm-md-template-command-styleTemplate, .cm-md-template-command-styleTemplate *": {
    color: "#f472b6 !important",
    backgroundColor: "rgba(244, 114, 182, 0.15) !important",
    fontSize: "12px !important",
  },
  ".cm-md-template-title, .cm-md-template-title *": {
    color: "#fde68a !important",
    backgroundColor: "rgba(253, 230, 138, 0.18) !important",
    textDecoration: "underline",
    textDecorationColor: "rgba(253, 230, 138, 0.6)",
    padding: "1px 6px !important",
    borderRadius: "3px !important",
    fontSize: "12px !important",
  },
  ".cm-md-template-done, .cm-md-template-done *": {
    color: "#34d399 !important",
    backgroundColor: "rgba(52, 211, 153, 0.15) !important",
    padding: "1px 6px !important",
    borderRadius: "3px !important",
    fontSize: "12px !important",
  },
  ".cm-md-template-in-progress, .cm-md-template-in-progress *": {
    color: "#fbbf24 !important",
    backgroundColor: "rgba(251, 191, 36, 0.15) !important",
    padding: "1px 6px !important",
    borderRadius: "3px !important",
    fontSize: "12px !important",
  },
  ".cm-md-template-id, .cm-md-template-id *": {
    color: "#f0abfc !important",
    backgroundColor: "rgba(240, 171, 252, 0.14) !important",
    padding: "1px 6px !important",
    borderRadius: "3px !important",
    fontWeight: "600 !important",
    fontSize: "12px !important",
  },
  ".cm-md-template-wt, .cm-md-template-wt *": {
    color: "#22d3ee !important",
    backgroundColor: "rgba(34, 211, 238, 0.14) !important",
    padding: "1px 6px !important",
    borderRadius: "3px !important",
    fontWeight: "600 !important",
    fontSize: "12px !important",
  },
  ".cm-md-template-start-line": {
    borderTop: "1px solid rgba(129, 140, 248, 0.2)",
    borderLeft: "1px solid rgba(129, 140, 248, 0.2)",
    borderRight: "1px solid rgba(129, 140, 248, 0.2)",
    borderBottom: "1px solid rgba(129, 140, 248, 0.2)",
    borderTopLeftRadius: "6px",
    borderTopRightRadius: "6px",
    backgroundColor: "rgba(129, 140, 248, 0.03)",
    paddingLeft: "6px",
    paddingRight: "96px",
    boxSizing: "border-box",
    paddingTop: "2px",
    paddingBottom: "2px",
  },
  ".cm-md-template-middle-line": {
    borderLeft: "1px solid rgba(129, 140, 248, 0.2)",
    borderRight: "1px solid rgba(129, 140, 248, 0.2)",
    backgroundColor: "rgba(129, 140, 248, 0.03)",
    paddingLeft: "6px",
  },
  ".cm-md-template-end-line": {
    borderBottom: "1px solid rgba(129, 140, 248, 0.2)",
    borderLeft: "1px solid rgba(129, 140, 248, 0.2)",
    borderRight: "1px solid rgba(129, 140, 248, 0.2)",
    borderBottomLeftRadius: "6px",
    borderBottomRightRadius: "6px",
    backgroundColor: "rgba(129, 140, 248, 0.03)",
    paddingLeft: "6px",
    paddingBottom: "2px",
  },
  ".cm-md-template-comment-line": {
    borderLeft: "1px solid rgba(129, 140, 248, 0.2)",
    borderRight: "1px solid rgba(129, 140, 248, 0.2)",
    backgroundColor: "rgba(129, 140, 248, 0.03)",
    paddingLeft: "6px",
  },
  ".cm-md-template-comment-line, .cm-md-template-comment-line *": {
    color: "#6b7280 !important",
    fontStyle: "italic !important",
  },
  ".cm-md-template-line-in-progress": {
    borderColor: "rgba(251, 191, 36, 0.35) !important",
  },
  ".cm-md-template-line-done": {
    borderColor: "rgba(52, 211, 153, 0.35) !important",
  },
  ".cm-md-template-hidden-line": {
    display: "none !important",
  },
  ".cm-md-design-mention, .cm-md-design-mention *": {
    color: "#f472b6 !important",
    fontWeight: "500",
    textDecoration: "underline",
    textDecorationColor: "rgba(244, 114, 182, 0.4)",
  },
  ".cm-md-agent-mention, .cm-md-agent-mention *": {
    color: "#7dd3fc !important",
    fontWeight: "500",
    textDecoration: "underline",
    textDecorationColor: "rgba(125, 211, 252, 0.4)",
  },
  ".cm-md-file-mention, .cm-md-file-mention *": {
    color: "#eab308 !important",
    fontWeight: "500",
    textDecoration: "underline",
    textDecorationColor: "rgba(234, 179, 8, 0.4)",
  },
  ".cm-md-referenced-file-mention, .cm-md-referenced-file-mention *": {
    color: "#c4b5fd !important",
    fontWeight: "500",
    textDecoration: "underline",
    textDecorationColor: "rgba(196, 181, 253, 0.4)",
  },
  ".cm-md-reference-project, .cm-md-reference-project *": {
    color: "#c4b5fd !important",
    fontWeight: "500",
  },
  ".cm-md-reference-folder, .cm-md-reference-folder *": {
    color: "#d97706 !important",
    fontWeight: "500",
  },
  ".cm-md-reference-file, .cm-md-reference-file *": {
    color: "#7dd3fc !important",
    fontWeight: "500",
  },
  ".cm-md-reference-image, .cm-md-reference-image *": {
    color: "#f9a8d4 !important",
    fontWeight: "500",
  },
  ".cm-md-reference-common, .cm-md-reference-common *": {
    color: "#cbd5e1 !important",
    fontWeight: "500",
  },
})
